### ISSUE TITLE
I have not found this paper online. Can you provide the paper?

### ISSUE THREAD

**Issue by limycml** [zzs1994/DJSRH#1]
I have not found this paper online. Can you provide the paper?

**Comment by zs-zhong** [comment]
Sorry for the late reply! The paper can be found:
http://openaccess.thecvf.com/content_ICCV_2019/papers/Su_Deep_Joint-Semantics_Reconstructing_Hashing_for_Large-Scale_Unsupervised_Cross-Modal_Retrieval_ICCV_2019_paper.pdf
