### ISSUE TITLE
S_I=S_I*2 -1

### ISSUE THREAD

**Issue by xinfangliu** [zzs1994/DJSRH#5]
why need this operation 'S_I=S_I*2 -1' after calculating the cos similarity matrix?

**Comment by zs-zhong** [comment]
Hi, due to `F_I = ImgNet.alexnet.features(x)`, F_I >= 0 (After ReLU). The original `S_I = F_I.mm(F_I.t())` is in [0, 1]. To limit it in [-1, 1], we apply `S_I = S_I * 2 - 1` here.

**Comment by xinfangliu** [comment]
> Hi, due to `F_I = ImgNet.alexnet.features(x)`, F_I >= 0 (After ReLU). The original `S_I = F_I.mm(F_I.t())` is in [0, 1]. To limit it in [-1, 1], we apply `S_I = S_I * 2 - 1` here.

I see. Thank you for your answer
